
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyzpsogefrexpwuzdppw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5enBzb2dlZnJleHB3dXpkcHB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NzA0NzMsImV4cCI6MjA1NzA0NjQ3M30.LtTMvJJ9Tc231si16zf6YPsUdAj7BLdIJvK9H90yozU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
